from __future__ import annotations

import json
from collections import defaultdict
from copy import deepcopy
from urllib.parse import urlparse

import httpx

from spec2event.adapters.portal.base import PortalSyncAdapter, PortalSyncItem, PortalSyncResult

_JSON_SCHEMA_DRAFT_07 = "http://json-schema.org/draft-07/schema#"


class SolaceEventPortalAdapter(PortalSyncAdapter):
    def __init__(self, *, base_url: str | None, token: str | None) -> None:
        self.base_url = _normalize_base_url(base_url)
        self.token = token

    def sync(self, canonical_model: dict) -> PortalSyncResult:
        event_definitions = _event_definitions(canonical_model)
        if not self.base_url or not self.token:
            items = []
            for definition in event_definitions:
                items.append(
                    PortalSyncItem(
                        artifact_type="event",
                        artifact_name=definition["canonicalEventName"],
                        status="not_configured",
                        manual_action=(
                            "Event Portal credentials are missing; use the "
                            "generated request payload to register manually."
                        ),
                        request_payload={
                            "name": definition["canonicalEventName"],
                            "topicName": definition["topicName"],
                            "schemaName": definition["schemaName"],
                        },
                    )
                )
            return PortalSyncResult(
                status="not_configured",
                message="Event Portal credentials are missing",
                items=items,
            )

        headers = {"Authorization": f"Bearer {self.token}", "Content-Type": "application/json"}
        client = _PortalClient(base_url=self.base_url, headers=headers)
        items: list[PortalSyncItem] = []

        domain_name = canonical_model.get("title") or canonical_model["serviceName"]
        domain_item = client.upsert_named(
            endpoint="/api/v2/architecture/applicationDomains",
            artifact_type="applicationDomain",
            artifact_name=domain_name,
            create_payload={
                "name": domain_name,
                "description": (
                    f"Application domain for {canonical_model['serviceName']} generated by "
                    "Micro Integration Factory."
                ),
            },
            lookup_params={"name": domain_name},
            match=lambda record: record.get("name") == domain_name,
        )
        items.append(domain_item)
        if domain_item.status != "completed" or not domain_item.external_id:
            return PortalSyncResult(
                status="partial",
                message=(
                    "Event Portal sync attempted but the application domain "
                    "could not be created"
                ),
                items=items,
            )
        application_domain_id = domain_item.external_id

        application_versions: dict[str, dict] = {}
        for application_name in canonical_model.get("applicationNames", []):
            application_item = client.upsert_named(
                endpoint="/api/v2/architecture/applications",
                artifact_type="application",
                artifact_name=application_name,
                create_payload={
                    "name": application_name,
                    "applicationDomainId": application_domain_id,
                    "applicationType": "standard",
                    "brokerType": "solace",
                },
                lookup_params={"name": application_name},
                match=lambda record, name=application_name: record.get("name") == name
                and record.get("applicationDomainId") == application_domain_id,
            )
            items.append(application_item)
            if application_item.status != "completed" or not application_item.external_id:
                continue

            application_version_item = client.upsert_named(
                endpoint="/api/v2/architecture/applicationVersions",
                artifact_type="applicationVersion",
                artifact_name=f"{application_name}:0.1.0",
                create_payload={
                    "applicationId": application_item.external_id,
                    "version": "0.1.0",
                    "displayName": "0.1.0",
                    "description": (
                        f"Generated {domain_name} producer application version created by "
                        "Micro Integration Factory from the uploaded contract."
                    ),
                    "stateId": "1",
                },
                lookup_params={
                    "applicationId": application_item.external_id,
                    "version": "0.1.0",
                },
                match=lambda record, application_id=application_item.external_id: record.get(
                    "applicationId"
                )
                == application_id
                and record.get("version") == "0.1.0",
            )
            items.append(application_version_item)
            if (
                application_version_item.status == "completed"
                and application_version_item.external_id
            ):
                application_versions[application_name] = {
                    "id": application_version_item.external_id,
                    "data": _payload_data(application_version_item.response_payload),
                }

        schema_versions: dict[str, str] = {}
        for definition in event_definitions:
            schema_item = client.upsert_named(
                endpoint="/api/v2/architecture/schemas",
                artifact_type="schema",
                artifact_name=definition["schemaName"],
                create_payload={
                    "name": definition["schemaName"],
                    "applicationDomainId": application_domain_id,
                    "schemaType": "jsonSchema",
                    "contentType": "json",
                },
                lookup_params={"name": definition["schemaName"]},
                match=lambda record, schema_name=definition["schemaName"]: record.get("name")
                == schema_name
                and record.get("applicationDomainId") == application_domain_id,
            )
            items.append(schema_item)
            if schema_item.status != "completed" or not schema_item.external_id:
                continue

            schema_version_item = client.upsert_named(
                endpoint="/api/v2/architecture/schemaVersions",
                artifact_type="schemaVersion",
                artifact_name=f"{definition['schemaName']}:0.1.0",
                create_payload={
                    "schemaId": schema_item.external_id,
                    "version": "0.1.0",
                    "displayName": "0.1.0",
                    "description": (
                        f"Generated JSON Schema version for {definition['schemaName']} from "
                        f"{canonical_model['serviceName']}."
                    ),
                    "content": json.dumps(definition["schemaContent"], sort_keys=True),
                    "stateId": "1",
                },
                lookup_params={
                    "schemaId": schema_item.external_id,
                    "version": "0.1.0",
                },
                match=lambda record, schema_id=schema_item.external_id: record.get("schemaId")
                == schema_id
                and record.get("version") == "0.1.0",
            )
            items.append(schema_version_item)
            if schema_version_item.status == "completed" and schema_version_item.external_id:
                schema_versions[definition["schemaName"]] = schema_version_item.external_id

        produced_event_version_ids: dict[str, list[str]] = defaultdict(list)
        for definition in event_definitions:
            event_item = client.upsert_named(
                endpoint="/api/v2/architecture/events",
                artifact_type="event",
                artifact_name=definition["canonicalEventName"],
                create_payload={
                    "name": definition["canonicalEventName"],
                    "applicationDomainId": application_domain_id,
                },
                lookup_params={"name": definition["canonicalEventName"]},
                match=lambda record, event_name=definition["canonicalEventName"]: record.get("name")
                == event_name
                and record.get("applicationDomainId") == application_domain_id,
            )
            items.append(event_item)
            if event_item.status != "completed" or not event_item.external_id:
                continue

            schema_version_id = schema_versions.get(definition["schemaName"])
            if not schema_version_id:
                items.append(
                    PortalSyncItem(
                        artifact_type="eventVersion",
                        artifact_name=f"{definition['canonicalEventName']}:0.1.0",
                        status="partial",
                        manual_action=(
                            f"Schema version for {definition['schemaName']} was not available; "
                            "event version was not linked."
                        ),
                    )
                )
                continue

            event_version_item = client.upsert_named(
                endpoint="/api/v2/architecture/eventVersions",
                artifact_type="eventVersion",
                artifact_name=f"{definition['canonicalEventName']}:0.1.0",
                create_payload={
                    "eventId": event_item.external_id,
                    "version": "0.1.0",
                    "displayName": "0.1.0",
                    "description": (
                        f"Generated event version for {definition['canonicalEventName']} "
                        f"published to {definition['topicName']}."
                    ),
                    "schemaVersionId": schema_version_id,
                    "stateId": "1",
                    "deliveryDescriptor": _delivery_descriptor(definition["topicName"]),
                },
                lookup_params={
                    "eventId": event_item.external_id,
                    "version": "0.1.0",
                },
                match=lambda record, event_id=event_item.external_id: record.get("eventId")
                == event_id
                and record.get("version") == "0.1.0",
            )
            items.append(event_version_item)
            if event_version_item.status == "completed" and event_version_item.external_id:
                produced_event_version_ids[definition["applicationName"]].append(
                    event_version_item.external_id
                )

        for application_name, application_version in application_versions.items():
            linked_event_version_ids = sorted(
                {
                    *(
                        application_version["data"].get("declaredProducedEventVersionIds")
                        or []
                    ),
                    *produced_event_version_ids.get(application_name, []),
                }
            )
            patch_item = client.patch_artifact(
                endpoint=f"/api/v2/architecture/applicationVersions/{application_version['id']}",
                artifact_type="applicationVersionFlow",
                artifact_name=f"{application_name}:0.1.0:produces",
                payload={"declaredProducedEventVersionIds": linked_event_version_ids},
            )
            items.append(patch_item)

        final_status = (
            "completed"
            if all(item.status == "completed" for item in items)
            else "partial"
        )
        return PortalSyncResult(
            status=final_status,
            message="Event Portal sync attempted",
            items=items,
        )


class _PortalClient:
    def __init__(self, *, base_url: str, headers: dict[str, str]) -> None:
        self.base_url = base_url
        self.headers = headers
        self._list_cache: dict[str, list[dict]] = {}

    def upsert_named(
        self,
        *,
        endpoint: str,
        artifact_type: str,
        artifact_name: str,
        create_payload: dict,
        lookup_params: dict | None = None,
        match,
    ) -> PortalSyncItem:
        try:
            existing = next(
                (
                    record
                    for record in self.list(endpoint, params=lookup_params)
                    if match(record)
                ),
                None,
            )
        except Exception as exc:  # noqa: BLE001
            return PortalSyncItem(
                artifact_type=artifact_type,
                artifact_name=artifact_name,
                status="partial",
                manual_action=str(exc),
                request_payload=create_payload,
                response_payload={"exception": str(exc)},
            )

        if existing:
            return PortalSyncItem(
                artifact_type=artifact_type,
                artifact_name=artifact_name,
                status="completed",
                external_id=_record_id(existing),
                request_payload=create_payload,
                response_payload={"data": existing},
            )

        return self.create_artifact(
            endpoint=endpoint,
            artifact_type=artifact_type,
            artifact_name=artifact_name,
            payload=create_payload,
        )

    def create_artifact(
        self,
        *,
        endpoint: str,
        artifact_type: str,
        artifact_name: str,
        payload: dict,
    ) -> PortalSyncItem:
        try:
            response = self._request("POST", endpoint, json=payload)
        except Exception as exc:  # noqa: BLE001
            return PortalSyncItem(
                artifact_type=artifact_type,
                artifact_name=artifact_name,
                status="partial",
                manual_action=str(exc),
                request_payload=payload,
                response_payload={"exception": str(exc)},
            )

        if response.status_code in {200, 201}:
            data = response.json()
            created = _payload_data(data)
            self._invalidate_cache(endpoint)
            return PortalSyncItem(
                artifact_type=artifact_type,
                artifact_name=artifact_name,
                status="completed",
                external_id=_record_id(created),
                request_payload=payload,
                response_payload=data,
            )

        return PortalSyncItem(
            artifact_type=artifact_type,
            artifact_name=artifact_name,
            status="partial",
            manual_action=f"HTTP {response.status_code}: {response.text[:400]}",
            request_payload=payload,
            response_payload={
                "statusCode": response.status_code,
                "body": response.text[:2000],
            },
        )

    def patch_artifact(
        self,
        *,
        endpoint: str,
        artifact_type: str,
        artifact_name: str,
        payload: dict,
    ) -> PortalSyncItem:
        try:
            response = self._request("PATCH", endpoint, json=payload)
        except Exception as exc:  # noqa: BLE001
            return PortalSyncItem(
                artifact_type=artifact_type,
                artifact_name=artifact_name,
                status="partial",
                manual_action=str(exc),
                request_payload=payload,
                response_payload={"exception": str(exc)},
            )

        if response.status_code in {200, 201}:
            data = response.json()
            self._invalidate_cache(endpoint.rsplit("/", 1)[0])
            return PortalSyncItem(
                artifact_type=artifact_type,
                artifact_name=artifact_name,
                status="completed",
                external_id=_record_id(_payload_data(data)),
                request_payload=payload,
                response_payload=data,
            )

        return PortalSyncItem(
            artifact_type=artifact_type,
            artifact_name=artifact_name,
            status="partial",
            manual_action=f"HTTP {response.status_code}: {response.text[:400]}",
            request_payload=payload,
            response_payload={
                "statusCode": response.status_code,
                "body": response.text[:2000],
            },
        )

    def list(self, endpoint: str, *, params: dict | None = None) -> list[dict]:
        cache_key = self._cache_key(endpoint, params)
        if cache_key in self._list_cache:
            return self._list_cache[cache_key]

        page = 1
        records: list[dict] = []
        while True:
            request_params = {"pageSize": 100, "pageNumber": page}
            if params:
                request_params.update(params)
            response = self._request("GET", endpoint, params=request_params)
            if response.status_code != 200:
                raise RuntimeError(f"HTTP {response.status_code}: {response.text[:400]}")

            data = response.json()
            page_records = data.get("data") or []
            if not isinstance(page_records, list):
                page_records = []
            records.extend(page_records)

            pagination = (data.get("meta") or {}).get("pagination") or {}
            next_page = pagination.get("nextPage")
            if not next_page:
                break
            page = int(next_page)

        self._list_cache[cache_key] = records
        return records

    def _request(
        self,
        method: str,
        endpoint: str,
        *,
        json: dict | None = None,
        params: dict | None = None,
    ) -> httpx.Response:
        return httpx.request(
            method,
            f"{self.base_url}{endpoint}",
            headers=self.headers,
            json=json,
            params=params,
            timeout=30.0,
        )

    def _cache_key(self, endpoint: str, params: dict | None) -> str:
        if endpoint.endswith("Versions"):
            return endpoint
        if not params:
            return endpoint
        parts = "&".join(f"{key}={params[key]}" for key in sorted(params))
        return f"{endpoint}?{parts}"

    def _invalidate_cache(self, endpoint_prefix: str) -> None:
        for key in list(self._list_cache):
            if key.startswith(endpoint_prefix):
                del self._list_cache[key]


def _normalize_base_url(base_url: str | None) -> str:
    if not base_url:
        return ""
    parsed = urlparse(base_url)
    if parsed.netloc == "api.solace.cloud":
        return "https://api.solace.cloud"
    if parsed.netloc.endswith("solace.cloud") and parsed.path.startswith("/ep/designer"):
        return "https://api.solace.cloud"
    return base_url.rstrip("/")


def _event_definitions(canonical_model: dict) -> list[dict]:
    by_key: dict[tuple[str, str], dict] = {}
    operations = canonical_model.get("operations", [])
    for operation in operations:
        request_schema = operation.get("requestSchema")
        for candidate in operation.get("eventCandidates", []):
            key = (candidate["applicationName"], candidate["canonicalEventName"])
            definition = by_key.setdefault(
                key,
                {
                    "applicationName": candidate["applicationName"],
                    "canonicalEventName": candidate["canonicalEventName"],
                    "topicName": candidate["topicName"],
                    "schemaName": candidate["schemaName"],
                    "requestSchemas": [],
                },
            )
            if request_schema:
                definition["requestSchemas"].append(request_schema)

    definitions = list(by_key.values())
    for definition in definitions:
        definition["schemaContent"] = _schema_content(
            definition["schemaName"],
            definition["requestSchemas"],
        )
        definition.pop("requestSchemas", None)
    return sorted(definitions, key=lambda item: item["canonicalEventName"])


def _schema_content(schema_name: str, request_schemas: list[dict]) -> dict:
    unique_schemas: list[dict] = []
    seen: set[str] = set()
    for schema in request_schemas:
        cleaned = _clean_schema(schema)
        marker = json.dumps(cleaned, sort_keys=True)
        if marker in seen:
            continue
        seen.add(marker)
        unique_schemas.append(cleaned)

    if not unique_schemas:
        base_schema: dict = {
            "type": "object",
            "additionalProperties": True,
        }
    elif len(unique_schemas) == 1:
        base_schema = unique_schemas[0]
    else:
        base_schema = {
            "oneOf": unique_schemas,
        }

    content = deepcopy(base_schema)
    content["$schema"] = _JSON_SCHEMA_DRAFT_07
    content["title"] = schema_name
    return content


def _clean_schema(schema: dict | None) -> dict:
    if not schema:
        return {"type": "object", "additionalProperties": True}

    if "allOf" in schema:
        return {
            "allOf": [_clean_schema(part) for part in schema.get("allOf", [])],
            **_schema_annotations(schema),
        }
    if "anyOf" in schema:
        return {
            "anyOf": [_clean_schema(part) for part in schema.get("anyOf", [])],
            **_schema_annotations(schema),
        }
    if "oneOf" in schema:
        return {
            "oneOf": [_clean_schema(part) for part in schema.get("oneOf", [])],
            **_schema_annotations(schema),
        }

    schema_type = schema.get("type")
    cleaned: dict = {}
    for key in [
        "type",
        "title",
        "description",
        "format",
        "enum",
        "required",
        "default",
        "pattern",
        "minLength",
        "maxLength",
        "minimum",
        "maximum",
        "minItems",
        "maxItems",
        "additionalProperties",
    ]:
        if key in schema:
            cleaned[key] = deepcopy(schema[key])

    if schema_type == "object" or "properties" in schema:
        cleaned["type"] = "object"
        cleaned["properties"] = {
            name: _clean_schema(property_schema)
            for name, property_schema in (schema.get("properties") or {}).items()
        }
        if "required" in schema:
            cleaned["required"] = deepcopy(schema["required"])
    elif schema_type == "array" or "items" in schema:
        cleaned["type"] = "array"
        cleaned["items"] = _clean_schema(schema.get("items") or {})

    return cleaned


def _schema_annotations(schema: dict) -> dict:
    annotations = {}
    for key in ["title", "description"]:
        if key in schema:
            annotations[key] = deepcopy(schema[key])
    return annotations


def _delivery_descriptor(topic_name: str) -> dict:
    return {
        "brokerType": "solace",
        "address": {
            "addressType": "topic",
            "addressLevels": [
                {
                    "name": segment,
                    "addressLevelType": "literal",
                }
                for segment in topic_name.split("/")
            ],
        },
    }


def _payload_data(payload: dict | None) -> dict:
    if not payload:
        return {}
    data = payload.get("data")
    if isinstance(data, dict):
        return data
    return payload


def _record_id(record: dict | None) -> str | None:
    if not record:
        return None
    return record.get("id")
